config/routes.rb
Tribally::Application.routes.draw do
 
resources :locations

ActiveAdmin.routes(self)

devise_for :admin_users, ActiveAdmin::Devise.config

resources :products do
	collection do 
		post "add_comment"
    post "create_offer"
    get "solar"
    post "product_group"
    get "solar_offers"
    get "solar_group_offers"
    get "solar_new_group_offers"
    #post "solar_offers"
	end
end

resources :businesses do
  collection do
    get "business_signup"
  end
end

  
resources :tribes do
    collection do
      get "change_invitation_status"
      get "my_tribe"
      get "tribe_products"
      get "i_want_this"
      post "invite_friend"
      get "solar"
     end
end
 


  root :to => "products#solar"
  devise_for :users,  :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  #devise_scope :user do
  #  get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  #end
  resources :users, :only => [:show, :index]
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  skip_before_filter :authenticate_user!  
  def index
    @businesses = Business.find(:all)
    
  end

  def show
    
    @business = Business.find(params[:id])
    #raise @business.user_id.inspect
    @user = User.where("_id" => @business.user_id)
    #@user.each do |each_details|
     # raise each_details.fname.inspect
    #end
    
  end

  def new 
    @business = Business.new    
  end

  def edit
    @business = Business.find(params[:id])
    #raise @business.website.inspect
    #raise @business.user.email.inspect
    @user = User.where("_id" => @business.user_id)
    #@business.user_id
    #@user.each do |each_details|
     # raise each_details.fname.inspect
    #end
    
  end

  def create
    #raise params.inspect
    @user = User.new(:fname => params[:fname], :email => params[:email], :password => params[:password], :password_confirmation => params[:password_confirmation], :role => "business")        
    if @user.save
      @user.businesses.create!(:website => params[:website])
      redirect_to @user, notice: 'Business was successfully created.'
    else
      render action: "new" 
    end
  end
  
  def update
    @business = Business.find(params[:id])
    
   #@business = Business.edit(:business_name => params[:fname], :business_email => params[:email])        
   @user = User.where("_id" => @business.user_id)
      if @business.update_attributes(params[:business])
        redirect_to @business, notice: 'Business was successfully updated.' 
      else
        render action: "edit" 
      end
  end

  
  def destroy
    @business = Business.find(params[:id])
    @business.destroy
     redirect_to businesses_url 
  end  
  def business_signup
    
  end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_form.html.erb
<%= form_for(@business , :html => { :multipart => true }) do |f|  %>
  <%  @user.each do |user| %>
      <%#=user.fname %>
 
      <div class="field">
      <%= f.label :business_name %>
      <%#= f.text_field :fname %>    
      <input type="text" value="<%= user.fname %>" />
      </div>

     <div class="field">
      <%= f.label :business_email %>
       <%#= f.text_field :email %>
       <input type="text" value="<%= user.email %>" /> 
     </div>
  <% end %>
      <div class="field">
        <%= f.label :website %>
        <%= f.text_field :website %>
      </div>
      <div class="field">
        <%= f.label :offers_history %>
        <%= f.text_field :offers_history %>
      </div>

      <div class="field">
        <%= f.label :invoices %>
        <%= f.text_field :invoices %>
      </div>
      <div class="field">
        <%= f.label :Account_data %>
        <%= f.text_field :account_data %>
      </div>
      
      <div class="field">
        <%= f.label :avatar %><br />
        <%= f.file_field :avatar %>
      </div>
    
       <div class="actions">
          <%= f.submit %>
       </div>
 <% end %>
  

app/views/businesses/business_signup.html.erb
<div class="business_sign_up_header">Create account with Tribally</div>
<div class="business_container">
  <div id="business_video"><iframe src="http://player.vimeo.com/video/26905273?title=0&amp;byline=0&amp;autoplay=0&amp;loop=0" width="560" height="320" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>
  <div class="business_last_line">
  Looking for Tribally personal accounts? click <a href="/users/sign_in">here</a>
  </div>
  <div class="business_signup_main_box"> 
    <%= form_tag businesses_path, :method => 'post' do %>

      <div class="business_sign_up_fields">
        <div class="business_fields1">Business name</div>
        <%= text_field_tag :business_name %>
      </div>
      <div class="business_sign_up_fields">
        <div class="business_fields1">Business email address</div> 
        <%= text_field_tag :business_email %>
      </div>

      <div class="business_sign_up_fields">
        <div class="business_fields">Business web address</div>
        <%= text_field_tag :website %>
      </div>

      <div class="business_sign_up_fields">
        <div class="business_fields">password </div>
        <%= password_field_tag :password %>
      </div>

      <div class="business_sign_up_fields">
        <div class="business_fields">password confirmation </div>
        <%= password_field_tag :password_confirmation %>
      </div>
    <div class="business_checkbox">
  <%= check_box_tag(:business_account) %>
      <p class="terms_and_conditions">
        I have accepted the <a href="#">terms and conditions </a>for Tribally business account</p>
    </div>
      <div class="business_sign_up_button_page"><%= submit_tag "Create account", :class =>'create_account_btn' %></div>
    <% end %>
  </div>
</div>
 

app/views/businesses/edit.html.erb
<h1>Editing business</h1>

<%= render 'form' %>

<%= link_to 'Show', @business %> |
<%= link_to 'Back', businesses_path %>

app/views/businesses/index.html.erb
<h1>Listing businesses</h1>

<table>
  <tr>
    <th> Business name </th>
    <th> Business email</th>
    <th> Website </th>
    <th> Offers history </th>
    <th> Invoices </th>
    <th> Account data </th>
  </tr>


  
    <% @businesses.each do |business| %>  
  <%#=business.user_id%>
 <%  @user = User.where("_id" => business.user_id) %>
 
  <tr>
    <%@user.each do |user_details|%>
    <td><%= user_details.fname %></td>
    <td><%= user_details.email %></td>
    <%end%>
    
    <td><%= business.website %></td>
    <td><%= business.offers_history%></td>
    <td><%= business.invoices%></td>
    <td><%= business.account_data%></td>
    <td><%= link_to 'Show', business %></td>
    <td><%= link_to 'Edit', edit_business_path(business) %></td>
    <td><%= link_to 'Destroy', business, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>

</table>

<br />

<%= link_to 'New Business', new_business_path %>

app/views/businesses/new.html.erb
<h1>New business</h1>
  <div class="business_sign_up_header">Create account with Tribally</div>
<div class="business_container">
  <div id="business_video"><iframe src="http://player.vimeo.com/video/26905273?title=0&amp;byline=0&amp;autoplay=0&amp;loop=0" width="560" height="320" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>
  <div class="business_last_line">
  Looking for Tribally personal accounts? click <a href="/users/sign_in">here</a>
  </div>
  <div class="business_signup_main_box"> 
    <%= form_tag @business, :method => 'post' do %>
      <div class="business_sign_up_fields">
        <div class="business_fields1">Business name</div>
        <%= text_field_tag :fname %>
      </div>
      <div class="business_sign_up_fields">
        <div class="business_fields1">Business email address</div> 
        <%= text_field_tag :email %>
      </div>

      <div class="business_sign_up_fields">
        <div class="business_fields">Business web address</div>
        <%= text_field_tag :website %>
      </div>

      <div class="business_sign_up_fields">
        <div class="business_fields">password </div>
        <%= password_field_tag :password %>
      </div>

      <div class="business_sign_up_fields">
        <div class="business_fields">password confirmation </div>
        <%= password_field_tag :password_confirmation %>
      </div>
    <div class="business_checkbox">
        <%#= check_box_tag :terms %>
       <input type="checkbox"  name="checkbox1" onclick="checkTerms();"/>
      <p class="terms_and_conditions">
        I have accepted the <a href="#">terms and conditions </a>for Tribally business account</p>
    </div>
      <div class="business_sign_up_button_page"><%= submit_tag "Create account", :class =>'create_account_btn' %></div>
    <% end %>
  </div>
</div>
  
  <script>
  function checkTerms() {
     if(document.business.checkbox1.checked)
     {
         document.business.commit.disabled=false;
     }
     else
     {
         document.business.commit.disabled=true;
     }
 }
  </script>


    
<%#= render 'business_signup' %>

<%= link_to 'Back', businesses_path %>

app/views/businesses/show.html.erb
<p id="notice"><%= notice %></p>
<%  @user.each do |each_details| %>
<p>
  <b>Business name:</b>
  <%= each_details.fname %>
</p>

<p>
  <b>Business email:</b>
  <%= each_details.email %>
</p>
<%end%>
<p>
  <b>Website:</b>
  <%= @business.website %>
</p>
<p>
  <b>Offers history:</b>
  <%= @business.offers_history %>
</p>
<p>
  <b>invoices:</b>
  <%= @business.invoices %>
</p>
<p>
  <b>Account data:</b>
  <%= @business.account_data %>
</p>
<div class="img_size">
<%= image_tag @business.avatar %>
</div>

 
<%= link_to 'Edit', edit_business_path(@business) %> |
<%= link_to 'Back', businesses_path %>