config/routes.rb
Tribally::Application.routes.draw do
 
resources :locations

ActiveAdmin.routes(self)

devise_for :admin_users, ActiveAdmin::Devise.config

resources :products do
	collection do 
		post "add_comment"
    post "create_offer"
    get "solar"
    post "product_group"
    get "solar_offers"
    get "solar_group_offers"
    get "solar_new_group_offers"
    #post "solar_offers"
	end
end

resources :businesses do
  collection do
    get "business_signup"
  end
end

  
resources :tribes do
    collection do
      get "change_invitation_status"
      get "my_tribe"
      get "tribe_products"
      get "i_want_this"
      post "invite_friend"
      get "solar"
     end
end
 


  root :to => "products#solar"
  devise_for :users,  :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  #devise_scope :user do
  #  get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  #end
  resources :users, :only => [:show, :index]
end

app/models/tribe.rb
class Tribe
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  include Mongoid::Timestamps::Updated
  
  #validates_associated :products
  
  #validates_presence_of :tribe_name, :message => "Please enter tribe name"
  #validates_presence_of :location, :message => "Please enter tribe location"  
  
  scope :location, where(:location => 'Hyderabad')

  belongs_to :member
  has_many :products
  embeds_many :members
  
  field :tribe_name, :type => String
  field :category, :type => String
  field :location, :type => String  
  field :offers, :type => String
  #field :amount_saved, :type => Integer
  field :created_by, :type => String
  field :members, :type => Array
  field :products, :type => Array
  

  #attr_accessible :tribe_name, :location, :product_name
  
  def self.i_want_this(tribe_id, product_name, uid)    
    product = Product.where(:tribe_id => tribe_id, :product_name => product_name).first    
    members_uid = all_member product
    if !members_uid.include?(uid)
      product.members.push([Member.new(:uid => uid, :status => 'accepted')])      
    end
  end

  
  def self.all_member product
    members_uid = []
    product.members.each do |each_member|
      members_uid.push(each_member.uid)
    end
    return members_uid
  end
  
 
   
  def self.search(search)
    if search
      
      where('tribe_name ?LIKE'  => "%#{search}%")
      #Tribe.find_by_tribe_name!('Tribe_name')
     #find(:all, :conditions =>['tribe.tribe_name LIKE ?', "%#{params[:search]}%"])
    
     
    else
      find(:all)
    end
  end


end

app/controllers/tribes_controller.rb
class TribesController < ApplicationController

  def index
    
   @tribes = Tribe.search(params[:search])
   
  end
  
  
  def show                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
    @tribe = Tribe.find(params[:id])
    @invitee_uid = []
    if !@tribe.members.blank?
      @tribe.members.each do |each_member|
        @invitee_uid.push(each_member.uid)
      end
    end    
  end
  
  def new
    @tribe = Tribe.new
    @tribe.products.build
  end

  def edit
    @tribe = Tribe.find(params[:id])
  end

  def create     
    @tribe = Tribe.new(params[:tribe])     
    if @tribe.save      
      @tribe.members.push(Member.new(:status => 'accepted', :uid => current_user.uid))
      if !params[:invitees].blank? 
        invitee_list = params[:invitees].split(",")      
        invitee_list.each do |each_invitee_uid|        
          @tribe.members.push(Member.new(:uid => each_invitee_uid))
        end
      end      
      @tribe.products.create(:product_name => params[:product_name], :members => [Member.new(:uid => current_user.uid)])
      redirect_to my_tribe_tribes_path, notice: 'Tribe was successfully created.'
    else      
      render action: "new"
    end
  end

  def update
    @tribe = Tribe.find(params[:id])

    if @tribe.update_attributes(params[:tribe])
      redirect_to @tribe, notice: 'Tribe was successfully updated.'
    else
      render action: "edit"
    end
    
  end

  def destroy
    @tribe = Tribe.find(params[:id])
    @tribe.destroy
    redirect_to tribes_path
  end
  
  def change_invitation_status
    @tribe = Tribe.where(:_id => params[:id]).first
    @tribe.members.each do |each_member|      
        if each_member.uid == params[:uid]
          each_member.update_attributes(:status => 'accepted')
        end
    end
    redirect_to my_tribe_tribes_path
  end
  
  def my_tribe    
    @tribes = Tribe.where('members.uid' => current_user.uid)
  end
  
  def tribe_products
    if params[:product_name]      
      @tribe = Tribe.where(:_id => params[:id]).first
      Tribe.i_want_this(params[:id], params[:product_name], current_user.uid)      
    else
      @tribe = Tribe.where(:_id => params[:id]).first
    end
  end
  
  def invite_friend
    @tribe = Tribe.where(:tribe_id => params[:tribe_id]).first
      if !params[:invitees].blank?
          invitee_list = params[:invitees].split(",")
          invitee_list.each do |each_invitee_uid|
            @tribe.members.push([Member.new(:uid => each_invitee_uid)])
      end
      else
      end
      redirect_to my_tribe_tribes_path
  end
  def solar
    
  end
  
  
  #def i_want_this    
  #  product = Product.where(:tribe_id => params[:tribe_id]).first
  #  product.members.push([Members.new(:uid => current_user.uid, :status => 'accepted')])
  #  raise "maisa"
  #end
    
end

app/helpers/tribes_helper.rb
module TribesHelper
  def no_of_wants(tribe_id, product_name, uid)    
    product = Product.where(:tribe_id => tribe_id, :product_name => product_name).first    
    members_uid = []
    product.members.each do |each_member|
      members_uid.push(each_member.uid)
    end
    return members_uid 
  end 
  
  def total_tribe_member(tribe)
    return tribe.members.count.size
  end
end

app/views/tribes/_invitations_my_tribe.html.erb
<%= stylesheet_link_tag('jquery.facebook.multifriend.select.css')%>
<%= javascript_include_tag('jquery.facebook.multifriend.select') %>

  <%= form_tag invite_friend_tribes_path do -%>
 
    <span>
        <input id = "aaaa" type="button" value="Invite Friend" class="<%= tribe.id %> global_button invite_friendbutton"/>
      <%= text_field_tag :invitees, nil , :id => "invitees_id", :class=> "hidden" %>
        <div id="jfmfs-container-wrapper" style="display: none">
        <div id="jfmfs-container">
        </div>
        </div>
    </span>
  


<script type="text/javascript" charset="utf-8">
(function($j) {
  var selectorObz = {
    filter_default: "Search By Name",
    friend_fields: "id,name,last_name&access_token="+'<%= current_user.facebook.access_token%>'
  }

  $j('.<%= tribe.id %>').live('click', function(){
    $j( "#jfmfs-container-wrapper" ).dialog({
      modal: true,
      resizable: false,
      closeText: "",
      position: 'center',
      title: 'Invite Participants',
      width: '726px',
      open: function(event, ui) { $j("#jfmfs-container").jfmfs(selectorObz); },
      buttons: {
  Invite: function() {
                var friendSelector = $j("#jfmfs-container").data('jfmfs');
                var selectedFriends = friendSelector.getSelectedIds();
                $j('#invitees_id').val(selectedFriends);
                $j('form').submit();
                $j(this).dialog( "close" );
              },
        Cancel: function() {
                $j("#jfmfs-container").data('jfmfs').clearSelected();
                $j('#aaaa').val("Invite Friend");
                $j(this).dialog( "close" );
              }

      }
    });
  })
})(jQuery);
</script>

<% end %>

app/views/tribes/_product_details.html.erb
<div class="products_sub_container">
  <div class="products_description_box">
    <% if product.description.nil? %>
     No description yet!
    <% else %>
      <%= product.description.nil? %>
    <% end %>
  </div>
  <div class="description_dotted_line"></div>
  <div class="products_offers_received_text">
    Offers for <%= product.product_name %> 
  </div>
  <div>
    <table class="data_table" cellpadding="0" cellspacing="0" border="0" style="opacity:1;">
      <thead>
        <tr>
          <th style="width:220px; border-right:1px solid #000;">company</th>
          <th style="width:220px; border-right:1px solid #000;">product</th>
          <th style="width:130px; border-right:1px solid #000;">price</th>
          <th style="width:100px; border-right:1px solid #000;">saving</th>
          <th style="width:200px;">min #</th>
        </tr>
      </thead>
      <tbody>
        <% if product.offers.empty? %>
            <td>no offers yet for this requested product. We're working to find great offers for your tribe soon.</td>
         <% else %>
           <% product.offers.each do |product_offers| %>
            <tr style="text-align:center;"  class="products_offers_list_box">
              <td>
                <div class="bussiness_logo_text">
                  Bussiness #X<br /><br />
                  (logo)
                </div>
              </td>
              <td>
                  <div>
                      <span class="offer_logo_box">
                        logo<br />
                        X
                      </span>
                          <div class="offer_name_text">
                              <%=  truncate(product_offers.offer_name, length: 40) %>
                          </div>
                          <div class="offer_description_text">
                              <%=  truncate(product_offers.offer_description, length: 90) %>
                          </div>
                  </div>
              </td>
              <td>
                <div class="retails_price_text">$<%=  product_offers.retails_price %></div> 
              </td>
              <td>
                <div class="offer_price_text">$<%=  product_offers.offer_price %></div>
              </td>
              <td>
                <div  class="number_of_buyers_text"><%=  product_offers.min_no_of_buyer %></div>
                <div class="members_needed_to_buy">
                    needed to by<br />
                    12/<%=  product_offers.min_no_of_buyer %> bought
                </div>
                <div><%= link_to "Accept this offer", '#', :class => 'orange_color_button'  %></div>
              </td>  
            </tr>
          <%end%>
        <% end %>
      </tbody>
    </table>     
  <% if !current_user.role.empty? %>
    <div id="offers_portal_box" class="products_offers_list_box">
      <div class="make_an_offer_text">Make an offer for this product</div>
         <%= form_tag create_offer_products_path, :methods => 'post' do %>
              <%= hidden_field_tag :product_id, product.id %>
              <%= hidden_field_tag :tribe_id, params[:id] %>
                <table>
                  <td class="bussiness_logo_box">
                      <div><%= text_field_tag :bussiness_logo %></div>
                      <%=  link_to "Change logo", '#', :class =>'global_button'%>
                  </td>
                  <td class="offers_logo_box">
                      <div><%= text_field_tag :offer_logo %></div>
                      <%=  link_to "Upload", '#', :class =>'global_button'%>
                  </td>
                  <td class="prices_offers">
                    <div class="offer_name_box">
                        <%= text_field_tag :offer_name %>
                        <span class="offers_name_size">Product name</span>
                    </div><br />
                    <div class="offer_description_text_align">
                        <%= text_area_tag :offer_description %>
                      <span class="offer_description_name_size">Product description</span>
                    </div>
                  </td>
                  <td>
                    <div class="offer_price_text_box">
                        <%= text_field_tag :offer_price %><br />
                        <span class="offer_price_text_size">Offer price</span>
                    </div>
                    <div class="offer_retail_price_text_box">
                        <%= text_field_tag :retails_price %><br />
                        <span class="offer_retails_price_text_size">
                          Retail price<br />
                          (Original price)
                        </span>
                    </div>
                  </td>
                  <td>
                    <div class="minimum_order_text_box">
                       <%= text_field_tag :min_no_of_buyer %><br /> 
                       <span class="min_order_text_size">Minimum order quantity</span>
                    </div>
                    <div class="offers_submit_button">
                        <%= submit_tag "Submit offer", :class =>'global_button' %>
                     </div>
                  </td>
                </table>
          <% end %>
     </div>
    <% end %>
    
     <script>
          $(".products_offers_list_box:even").css("background-color","#D0D0D0"); 
          $(".products_offers_list_box:odd").css("background-color","#E8E8E8"); 
      </script>
    </div><br />
</div> 

<div class="comments_header">Comments</div>
<% if product.comments.empty? %>
  <div class="No_comments_header">
    <span class="No_comments_text">No comments yet.</span>
    <span class="mylink" id="#<%= product._id %>">Leave a comment</span>
  </div>
  <div id="<%= product._id %>" class="comments_body_box" style ="display:none">
    <%= form_tag add_comment_products_path do  %>
      <div class="field">	      
        <%= hidden_field_tag :product_id, product._id %>
        <%= hidden_field_tag :user_id, current_user.uid %>
      </div>                    
      <div class="field">
        <%= text_area_tag :body %>
      </div>
      <div class="actions">
      <%= submit_tag("Submit") %>
      </div>
    <% end %>
  </div>        
<% else %>
  <% product.comments.each do |product_comments| %>
    <div class="comments_text_box">
      <span class="comments_user_name"><%= FbGraph::User.new(product_comments.user_id).fetch.name %></span>:
      <%= product_comments.body %>
    </div>
  <% end %>
   <div class="mylink" id="#<%= product._id %>">Leave a comment</div>
   <div id="<%= product._id %>" class="comments_body_box" style ="display:none">
    <%= form_tag add_comment_products_path do  %>
      <div class="field">	      
        <%= hidden_field_tag :product_id, product._id %>
        <%= hidden_field_tag :user_id, current_user.uid %>
      </div>                    
      <div class="field">
        <%= text_area_tag :body %>
      </div>
      <div class="actions">
      <%= submit_tag "Submit", :class => 'global_button' %>
      </div>
    <% end %>
  </div>     
<% end %>     
<br />

app/views/tribes/edit.html.erb
<h1>Editing tribe</h1>

<%= render 'form' %>

<%= link_to 'Show', @tribe %> |
<%= link_to 'Back', tribes_path %>

app/views/tribes/i_want_this.js.erb
<% if !@user.nil?%>
  $('#email_validate_lbl').text("Email Already Exist...!");
<% else%>
  $('#email_validate_lb2').text("");
<% end%>

app/views/tribes/index.html.erb
  <div class="my_tribe">
    <div class="dimension_tribe_name">All Tribes
    </div>
  </div>
      <div class="search_tribe_box">
        
        
          <%= form_tag tribes_path, :method => 'get' do  %>
        <p>
            <%= text_field_tag :search, params[:search] %>      
            <%= submit_tag "Search", :name => nil, :class => 'global_button' %>
        </p>
        
          <% end %>
      </div>

<% @tribes.each do |tribe| %>
  <br />
  <div class="my_tribe_page">
     <div class="my_tribe_name_dimension">
       <div class="my_tribe_name"><%= tribe.tribe_name %></div>
           <div class="my_tribe_f">
            
              <div class="addthis_toolbox addthis_default_style"  id="fb_dimension">
                 <a class="addthis_button_facebook_like at300b" width="80px" style="width :75px;" addthis:url=" http://localhost:3000/tribes/tribe_products?id=<%= tribe.id %>"></a>            
                <a class="addthis_button_tweet" addthis:url="http://localhost:3000/tribes/tribe_products?id=<%= tribe.id %>"></a>
            </div>
            <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=xa-501a736c01ef1239"></script>
           </div>
      </div>
   
    
     <div class="tribe_links">
       <%=  link_to "Go to this tribe", tribe_products_tribes_path(:id => tribe), :class => 'global_button', :id => 'go_to_this_tribe' %>
       <% tribe.members.each do |each_member| %>
        <% if  each_member['uid'] == current_user.uid && each_member['status'] == 'thinking' %>                              
            <%= link_to "Accept Invitation", change_invitation_status_tribes_path(:id => tribe.id, :uid => each_member['uid']), :class => 'global_button', :id => ' accept_invitation_button' %>
        <% elsif each_member['uid'] == current_user.uid && each_member['status'] == 'accepted' %>                              
            <%= submit_tag 'Invite Friend', :class => 'global_button', :id =>'invite_friend' %>
   
        <% end %>
      <% end %>
     </div>
     <div class="my_details">
        <div>
         <%#= link_to (image_tag(FbGraph::User.new(tribe.created_by).fetch.picture, :class => 'created_user_image2' )) %>
        </div>
        <p class="tribe_created_text2">Tribe created by</p>
        <p class="tribe_created_user_name2"> <%#= FbGraph::User.new(tribe.created_by).fetch.name %></p> 

     </div> 
  </div>
  
<% end %>
<div class="my_tribe_last"> 
  <p class="my_tribe_last_line">Can't see what you want? Click to <%= link_to "Create a tribe", new_tribe_path %></p>
</div>

app/views/tribes/my_tribe.html.erb
<p class="my_tribe">My Tribes</p>
<% @tribes.each do |tribe| %>
  <br />
  
  <div class="my_tribe_page">
     <div class="my_tribe_name_dimension">
       <div class="my_tribe_name"><%= tribe.tribe_name %></div>
           <div class="my_tribe_f">
            
              <div class="addthis_toolbox addthis_default_style"  id="fb_dimension">
                
                
                <a class="addthis_button_facebook_like at300b" width="80px" style="width :75px;" addthis:url=" http://localhost:3000/tribes/tribe_products?id=<%= tribe.id %>" ></a>
                <a class="addthis_button_tweet" addthis:url="http://localhost:3000/tribes/tribe_products?id=<%= tribe.id %>"></a>
            
              </div>
            <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=xa-501a736c01ef1239"></script>
           </div>
      </div>
   
    
     <div class="tribe_links">
       <%=  link_to "Go to this tribe", tribe_products_tribes_path(:id => tribe), :class => 'global_button', :id => 'go_to_this_tribe' %>
       <% tribe.members.each do |each_member| %>
        <% if  each_member['uid'] == current_user.uid && each_member['status'] == 'thinking' %>                              
            <%= link_to "Accept Invitation", change_invitation_status_tribes_path(:id => tribe.id, :uid => each_member['uid']), :class => 'global_button', :id => ' accept_invitation_button' %>
        <% elsif each_member['uid'] == current_user.uid && each_member['status'] == 'accepted' %>                               
             <% if current_user.provider == 'facebook' %>
                  <%= render :partial => 'invitations_my_tribe',:locals => {:tribe => tribe} %>
            <% end %> 
        <% end %>
      <% end %>
     </div>
     <div class="my_details">
        <div>
         <%= link_to (image_tag(FbGraph::User.new(tribe.created_by).fetch.picture, :class => 'created_user_image2' )) %>
        </div>
        <p class="tribe_created_text2">Tribe created by</p>
        <p class="tribe_created_user_name2"> <%= FbGraph::User.new(tribe.created_by).fetch.name %></p> 

     </div> 
  </div>
  
<% end %>
<div class="my_tribe_last"> 
  <p class="my_tribe_last_line">Can't see what you want? Click to <%= link_to "Create a tribe", new_tribe_path %></p>
</div>

app/views/tribes/new.html.erb
<section class="info">
  <h2>Create a tribe to save money</h2>
  <div>Create a tribe to save money buying what you want with a group of people.</div>
  </br>
  <div id="devider"></div>
  <%= render 'form' %>

</section>

app/views/tribes/show.html.erb
<%= javascript_include_tag('messages')%>

<% if !@invitee_uid.blank? %>
  <script type="text/javascript" charset="utf-8">
    
    $.tribally.renderSendBox(<%= "'"+@tribe.tribe_name + "'" %>, <%= "'"+@invitee_uid.join(",") +"'"%>, <%= "'http://tribally-new.herokuapp.com/" + "'"%>, <%=  "'"+ tribe_url(@tribe) +"'"%>, fbCallback).replace("'", "");    
    
    function fbCallback(response){
      if(response == null){
        //alert("fail");
      } else
      {          
        //var srt = '<%#= params[:id] %>';
        //alert("success"+srt);
        //jQuery.support.cors = true;
        //$.get('/challenges/update_status_af_meg', 
        //{thinking_abt:srt},
        //function(data) {

        //}, 'script'
      //);
      }
    }
        
  </script>
<% end %>
  
<p>
<b>Tribe first product:</b>  
<% @tribe.products.each do |each_product| %>
  <%= each_product['product_name'] %>
<% end %>
</p>  
<p>
  <b>Tribe location:</b>
  <%= @tribe.location %>
</p>

<p>
  <b>Tribe name:</b>
  <%= @tribe.tribe_name %>
</p>

<p>
  <b>Tribe category:</b>
  <%= @tribe.category %>
</p>

<p>
  <b>Tribe members:</b>
    <% @tribe.members.each do |each_member| %>    
      <%= FbGraph::User.new(each_member['uid']).fetch.name %>
      <%= image_tag(FbGraph::User.new(each_member['uid']).fetch.picture) %>
    <% end %>
</p>

app/views/tribes/tribe_products.html.erb
<table>
  <td class="my_tribe_name_dimension2">
    <div class="tribe_name_box"><%= @tribe.tribe_name %>
    
     <div class="addthis_toolbox addthis_default_style"  id="fb_dimension">
         <a class="addthis_button_facebook_like at300b" fb:like:layout="button_count" style="width :75px;"></a>
        <a class="addthis_button_tweet" id ="t_dimension"></a>
        
     </div>
      <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=xa-501a736c01ef1239"></script>
      </div>
  </td>
  
      
  
  <td class="add_friends_to_tribe">
     <div>
      <%= total_tribe_member(@tribe) %> members<br />
      <!--
      <script>
        $(function() {
          $( "#autocomplete-input" ).autocomplete({
            source: function( request, response ) {
            $.ajax({
              url: "https://graph.facebook.com/me/friends?access_token=<%= current_user.token %>&callback=?",
              dataType: "jsonp",
              data: {
              width: 250,
              height: 400,
              max: 8,
              cacheLength: 10,
              minChars: 1,
                featureClass: "P",
                style: "full",
                maxRows: "5",
                name_startsWith: request.term
              },
              success: function( data ) {
                res = $.map( data.data, function( item ) {
                  if (item.name.toLowerCase().indexOf(request.term.toLowerCase()) >= 0){
                    return {
                      label: item.name,
                      value: item.id
                    }
                  }
                });
                response(res);
              }
            });
          },
          minLength: 0,
          select: function( event, ui ) {
            // log( ui.item ?
            // "Selected: " + ui.item.label :
            // "Nothing selected, input was " + this.value);
          },
          open: function() {
            $( this ).removeClass( "ui-corner-all" ).addClass( "ui-corner-top" );
          },
          close: function() {
            $( this ).removeClass( "ui-corner-top" ).addClass( "ui-corner-all" );
          }
          });
         
         $("#autocomplete-input").data("autocomplete")._renderItem =  function( ul, item ) {
           var image_url = "http://graph.facebook.com/" + item.value +"/picture";
           return $( "<li style='height:40px;'>" ).append($("<img style='float:left;height:35px;'>").attr('src',image_url))
           .append( $( "<a>" ).text( item.label ) )
           .appendTo( '#friendslist' );
         }
        });
      </script>
      <ul>
        <li>
         <input id="autocomplete-input" />
        </li>
      </ul>
      <div id="friendslist"></div> 
      -->
      <input type="text" class="input_fb_user_name" placeholder="+Add Friends to group"/>
    </div>
    <%= link_to 'Invite friends', "#", :class =>'orange_color_button_a' %>
        
    <%= link_to 'Leave this tribe', "#", :class =>'orange_color_button_a' %>  
  </td>
  <td>
    <section id="tribe_create">
      <table>
        <td>
          <%= link_to (image_tag(FbGraph::User.new(@tribe.created_by).fetch.picture, :class => 'created_user_image' )) %>
        </td>
        <td>          
          <div class="tribe_created_text">Tribe created by:</div>
          <div class="tribe_created_user_name"> <%= FbGraph::User.new(@tribe.created_by).fetch.name %></div>
          
         
          <table cellpadding="0" cellspacing="0" width="133" class="created_user_ratings">
          <tr>
            <td>
              <iframe src="http://www.ratingcode.com/show.php?id=13442292269&st=2&bg=FFFFFF" border="0" width="115" height="37" marginwidth="0" margin-left="60px" marginheight="0" hspace="0" vspace="0" frameborder="0" scrolling="no" bgcolor=FFFFFF ></iframe>
            </td>
            </tr>
          </table>

        </td>
      </table>
    </section>
  </td>
</table>

<div class="request_product_box">  
  <table>
    <td>
      <%= link_to image_tag("/assets/plus_icon.png", :class => 'plus_icon') %>
    </td>      
    <td>
      <div class="request_input_box_border">        
        <%= text_field_tag 'search', nil, :class => 'request_input_box', :placeholder => 'Search product' %>
      </div>
    </td>                  
    <%= form_tag("/products", :method => "post") do %>
      <td width="300" align="center">        
        <%= submit_tag 'Request new product', :class =>'global_button' %>
      </td>
      <td>      
        <%= hidden_field_tag :tribe, @tribe._id %>
        <%= text_field_tag 'product_name', nil, :class => 'request_input_box', :placeholder => 'Request new product' %>      
      </td>
    <% end %>
  </table>       
</div><br />
<% product_count = 0 %>
<% @tribe.products.each do |product| %>  
  <div class="products_main_container">
    <div class="product_offers_time_box">
      <table>
          <td>
           <% if product_count == 0 %>
              <div class="show_hide_box">
                <input type="button" value = 'Hide' class="button" id = "<%= product.id %>aaa" />
            <% else %>
                <input type="button" value = 'Show' class="button" id = "<%= product.id %>aaa" />              
              </div>
            <% end %> 
             <script>
              $('document').ready(function(){
                $("#<%= product.id %>aaa").css('background',"url(/assets/loginArrow.png) no-repeat 8px -87px");
                $("#<%= product.id %>aaa").click(function(){
                  
                  var attr_value = $('#<%= product.id %>aaa').attr('value');      
                  $("#<%= product.id %>aaaa").toggle('fast');
                  
                  if(attr_value == 'Hide')
                    {          
                      $("#<%= product.id %>aaa").attr('value','Show');
                      $("#<%= product.id %>aaa").css('background',"url(/assets/loginArrow.png)no-repeat 8px -5px");
                    }
                    else if(attr_value == 'Show'){          
                      $("#<%= product.id %>aaa").attr('value','Hide');
                      $("#<%= product.id %>aaa").css('background',"url(/assets/loginArrow.png) no-repeat 8px -87px");
                    }
                });    
              });
            </script>
          </td>
          <td>
            <div class="product_offers_small_box">
              <table style="margin-top:7px;">
                  <td style="width:200px;">
                    <span class="product_offers_box_text">Product</span><br/>
                    <span class="product_offers_box_text2"><%= truncate(product.product_name, length: 20) %></span>
                  </td>
                  <td style="width:80px; text-align:center;">
                    <span class="product_offers_box_text">Offers</span><br />
                    <span  class="product_offers_box_text3"><%= product.offers.count %></span>
                  </td>
              </table>
            </div>
          </td>
          <td>
            <div class="products_want_this_box">
              <div class="wants_box"> 
                <span class="want_number"><%# @ad = no_of_wants(params[:id], product.product_name, current_user.uid )  %></span>
                <%#= @ad.size %><br/><span class="size">Wants this</span>              
                <div class="i_want_this">
                  <%= link_to "I want this", tribe_products_tribes_path(:id => params[:id], :product_name => product.product_name), :class => 'global_button' %>                
                </div>
              </div> 
            </div>
          </td>
          <td>            
            <div class="products_contdown_time_box"> 
              <div id="time_left_to_open">
                <div id="<%= product.id %>a"></div>
              </div>
               <div id="time_left_to_open"></div>               
               <div id="<%= product.id %>a"></div>  
               <div id="time"><b>OPEN</b></div>
               <script>
                 var newYear = new Date(); 
                 newYear = new Date(newYear.getFullYear() + 1, 1 - 1, 1);                 
                 $('#<%= product.id %>a').countdown({until: newYear, format: 'dHMS'}); 
               </script>
            </div>
          </td>
        </table>
    </div>
    <% if product_count == 0 %>
      <div  id="<%= product.id %>aaaa">
        <%= render 'product_details', :product => product %>
      </div>
    <% else %>
      <div  id="<%= product.id %>aaaa" style="display: none">
        <%= render 'product_details', :product => product %>
      </div>
    <% end %>
    
    <% product_count += 1 %>
  </div><br />
<% end %>

<script>
 $(function(){
   $('.mylink').click(function(event){      
      $(event.target.id).toggle();      
   });
});
</script>