config/routes.rb
Tribally::Application.routes.draw do
 
resources :locations

ActiveAdmin.routes(self)

devise_for :admin_users, ActiveAdmin::Devise.config

resources :products do
	collection do 
		post "add_comment"
    post "create_offer"
    get "solar"
    post "product_group"
    get "solar_offers"
    get "solar_group_offers"
    get "solar_new_group_offers"
    #post "solar_offers"
	end
end

resources :businesses do
  collection do
    get "business_signup"
  end
end

  
resources :tribes do
    collection do
      get "change_invitation_status"
      get "my_tribe"
      get "tribe_products"
      get "i_want_this"
      post "invite_friend"
      get "solar"
     end
end
 


  root :to => "products#solar"
  devise_for :users,  :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  #devise_scope :user do
  #  get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  #end
  resources :users, :only => [:show, :index]
end

app/models/product.rb
class Product
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  include Mongoid::Timestamps::Updated
  
  
  embeds_many :offers
  belongs_to :tribe
  embeds_many :comments  
  embeds_many :product_groups  
  
  #validates_presence_of :product_name, :message => "Please enter tribe first product"
  
  field :business_name, :type => String
  field :members, :type => String
  field :product_name, :type => String
  field :description, :type => String
  field :product_url, :type => String
  field :price, :type => String
  field :offers, :type => Array
  field :postcode, :type => String
  field :map_lat, :type => Float
  field :map_lng, :type => Float
  field :street_address, :type => String
  field :suburb, :type => String
  field :state, :type => String
  
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
    if params[:query]
      @products = Product.all(:conditions => ["product_name LIKE ?", "%#{params[:query]}%"], :order => 'name', :limit => 5)
    else
      # @products = Product.all
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.json do
        if params[:type] == "full"
          render :json => @products.map(&:_as_json)
        else
          render :json => @products.map(&:name)
        end
      end
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
    @product.offers.build 
    #@product.product_groups.build 
  end

  def edit
    @product = Product.find(params[:id])
    as = @product.offers
  end

  def create
    @tribe = Tribe.where(:_id => params[:tribe]).first
    @tribe.products.create(:product_name => params[:product_name], :members => [Member.new(:uid => current_user.uid)])
    redirect_to tribe_products_tribes_path(:id => @tribe._id)
  end

  def update
    @product = Product.find(params[:id])
    @product.offers.destroy
    #@product.destroy
      if @product.update_attributes(params[:product])
        redirect_to @product, notice: 'Product was successfully updated.'
      else
        render action: "edit"
      end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_url
  end

  def add_comment
    product = Product.where(:_id => params[:product_id]).first
    product.comments.push([Comment.new(:user_id => params[:user_id], :body => params[:body])])
    redirect_to tribe_products_tribes_path(:id => product.tribe_id.to_s)
  end
  
  def create_offer
    product = Product.where(:_id => params[:product_id]).first
    product.offers.push([Offer.new(:retails_price => params[:retails_price],:min_no_of_buyer => params[:min_no_of_buyer], \
    :offer_name => params[:offer_name], :offer_description => params[:offer_description], :offer_price => params[:offer_price])])
    redirect_to tribe_products_tribes_path(:id => product.tribe_id.to_s)
  end
  def solar
    
  end
  
  def product_group   
   product = Product.all.first
   if Product.where("product_groups.zipcode" => params[:product][:zipcode]).first.nil?
   product.product_groups.push([ProductGroup.new(:zipcode => params[:product][:zipcode], :map_lng => params[:product][:map_lng], :map_lat => params[:product][:map_lat])]) 
   #render :text=>"text"
   redirect_to solar_new_group_offers_products_path(:zipcode => params[:product][:zipcode])
   else
      redirect_to solar_group_offers_products_path(:zipcode => params[:product][:zipcode])
   end     
  end
  
  
  def solar_offers  
    @zipcode = params[:zipcode]
    @group_details = Product.where("product_groups.zipcode" => params[:zipcode]).first

    #render :text => @group_details.inspect and return    
    @group_details.product_groups.each do |each_product_group|
      if each_product_group.zipcode == params[:zipcode]
        @current_zipcode = each_product_group 
      end
    end
  end
  
  def solar_group_offers
     @product = Product.all.first
     @zipcode = params[:zipcode]
     @zipcode = Product.where("product_groups.zipcode" => params[:zipcode]).first
   

     #raise params[:zipcode].inspect
     @first_product = Product.all.first
     @first_product.product_groups.each do |each_product_group|
        if each_product_group.zipcode == params[:zipcode]
          @searched_group = each_product_group
        end
     end     
  
       

  end
  def solar_new_group_offers
    @zipcode = params[:zipcode]
    @first_product = Product.all.first
     @first_product.product_groups.each do |each_product_group|
        if each_product_group.zipcode == params[:zipcode]
          @searched_group = each_product_group
        end
     end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def people(zipcode)
    @group_details = Product.all.first
    @group_details.product_groups.each do |each_product_group|
      if each_product_group.zipcode == zipcode
        return each_product_group.members.count 
      end
    end
  end
  
  def no_of_offers(zipcode)
    return 5
  end
  
  def is_member(zipcode,current_uesr_uid)
    @all_member = []
    @group_details = Product.all.first
    @group_details.product_groups.each do |each_product_group|
      if each_product_group.zipcode == zipcode
        each_product_group.members.each do |each_member| 
          @all_member.push(each_member.uid)
        end
      end
    end
    return @all_member.include?(current_uesr_uid)
  end
end

app/views/products/_comment.html.erb
<div><%=current_user.id%></div>
<div><%=text_area_tag 'comment[text_comment]'%></div>
<div><button class="action">Submit</button></div>


  

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   

  <div class="field">
    <%= f.label :business_name %>
    <%= f.text_field :business_name %>
  </div>
  <div class="field">
    <%= f.label :members %>
    <%= f.text_field :members %>
  </div>
  <div class="field">
    <%= f.label :product_name %>
    <%= f.text_field :product_name %>
  </div>
  <div class="field" id="product_description">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div><br/><br />
  <div class="field">
    <%= f.label :product_url %>
    <%= f.text_field :product_url %>
  </div>
  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>
  
  <% @product.offers.each_with_index do |offer, index| %>
  <%= f.fields_for "offers[]", offer do |offer_fields| %>
    <div class="field">
      <%= offer_fields.label :price_discount %>
      <%= offer_fields.text_field :price_discount %>
    </div>
    <div class="field">
      <%= offer_fields.label :minimum_order_quantity %>
      <%= offer_fields.text_field :min_no_of_buyer %>
    </div>
  <% end %>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>
<br />
<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<table>
  <tr>
    <th>Business name</th>
    <th>Members</th>
    <th>Product name</th>
    <th>Description</th>
    <th>Product url</th>
    <th>Price</th>
    <th>Price discount</th>
    <th>Min order quantity</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.business_name %></td>
    <td><%= product.members %></td>
    <td><%= product.product_name %></td>
    <td><%= product.description %></td>
    <td><%= product.product_url %></td>
    <td><%= product.price %></td>
    
      <% product.offers.each do |each_offer| %>
       <td> <%= each_offer['price_discount'] %></td>
       <td> <%= each_offer['min_no_of_buyer'] %> </td>
      <% end %>
    
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<%= link_to 'New Product', new_product_path %>
<!--
<br /><br />
<div class="request_product_box">
  <table>
    <td>
      <%= link_to image_tag("/assets/plus_icon.png", :class => 'plus_icon') %>
    </td>
    <td>
    <div class="request_input_box_border">
      <%= text_field_tag 'request', nil, :class => 'request_input_box' %>
    </div>
    </td>
    <td>
     <%= link_to image_tag("/assets/request_product_icon.png", :class => 'request_product_icon') %>
    </td>
  </table>
</div><br />
-->
<% @products.each do |product| %>
  <div class="products_main_container">
      <div class="product_offers_time_box">
        <table>
          <td>
            <div>
              <span onclick="toggle_visibility('hiding');">Hide</span>
              <script type="text/javascript">
                  function toggle_visibility(id) {
                     var e = document.getElementById(id);
                     if(e.style.display == 'block')
                        e.style.display = 'none';
                     else
                        e.style.display = 'block';
                  }
              </script>
            </div>
          </td>
          <td>
            <div class="product_offers_small_box">
              <table style="margin-top:7px;">
                  <td style="width:200px;">
                    <span class="product_offers_box_text">Product</span><br/>
                    <span class="product_offers_box_text2"><%= product.product_name %></span>
                  </td>
                  <td style="width:80px; text-align:center;">
                    <span class="product_offers_box_text">Offers</span><br />
                    <span  class="product_offers_box_text3"><%= product.offers.count %></span>
                  </td>
              </table>
            </div>
          </td>
          <td>
            <div class="products_want_this_box"> 
                <div id="variableVal">0</div>
                    <input type="button" onclick="add()" value="I want this">
                    <script>
                      var myNumber = 0; // better don't use number as your variable's name.
                    function add() {
                    myNumber++;
                    document.getElementById("variableVal").innerHTML = myNumber;
                    }
                      </script>
            </div>
          </td>
          <td>
            
            <div class="products_contdown_time_box">
              
                   <div id="counter-container">
                    <div class="counter-box">
                      <div class="counter"><span id="d" class="counter-p">#</span></div>
                      <span class="counter-box-p">days</span>
                    </div>
                    <div class="counter-box">
                      <div class="counter"><span id="h" class="counter-p">#</span></div>
                      <span class="counter-box-p">hours</span>
                    </div>
                    <!-- <div class="counter-box">
                      <div class="counter"><span id="m" class="counter-p">#</span></div>
                      <span class="counter-box-p">minutes</span>
                    </div>
                    <div class="counter-box">
                      <div class="counter"><span id="s" class="counter-p">#</span></div>
                      <span class="counter-box-p">seconds</span>
                    </div> -->
                  </div>
               
                 <script>
                   function counter(futureDate) {
                        var today = new Date(2012,7,24); // today
                        count = Math.floor((futureDate-today)/1000);
                        countdown = setInterval(function(){
                          var temp;
                          $("span#d").html(Math.floor(count/(60*60*24)));
                          temp = count%(60*60*24);
                          $("span#h").html(Math.floor(temp/(60*60)));
                          temp = count%(60*60);
                          $("span#m").html(Math.floor(temp/(60)));
                          temp = count%(60);
                          $("span#s").html(temp);
                          if (count === 0) {
                               alert("time's up");
                               clearInterval(countdown);       
                          }
                          count--;
                        }, 1000);
                      }

                      counter(new Date(2012,8,26)); // May 8, 2012 00:00:00
                      /* counter(new Date(2012,4,8,15,49,10)); // May 8, 2012 15:49:00 */
              </script>
            </div>
            
          </td>
        </table>
      </div>
      <div  id="hiding">
      <div class="products_sub_container">
        <div class="products_description_box">
           <%= product.description %>
        </div>
        <div class="description_dotted_line"></div>
        <div class="products_offers_received_text">
          Offers Received
        </div>
        <div>
          <table class="data_table" cellpadding="0" cellspacing="0" border="0" style="opacity:1;">
            <thead>
              <tr>
                <th style="width:220px; border-right:1px solid #000;">company</th>
                <th style="width:250px; border-right:1px solid #000;">product</th>
                <th style="width:150px; border-right:1px solid #000;">price</th>
                <th style="width:100px; border-right:1px solid #000;">time of bid</th>
                <th style="width:200px;">min #</th>
              </tr>
            </thead>
            <tbody>
              <tr style="text-align:center;">
                <td><%= product.business_name %></td>
                <td><%= product.product_name %></td>
                <td><%= product.price %></td>
                <td>time</td>
                <% product.offers.each do |each_offer| %>
                 <td> <%= each_offer['min_no_of_buyer'] %> </td>
                <% end %>
              </tr>
            </tbody>
          </table>             
       </div>
</div>
</div>

<div class="myclassname">
<a href="#" class="mylink">Comment</a>
<div class="products_comments_box" id="hiding2">
  <%= form_tag add_comment_products_path do  %>
            <div class="field">	      
	      <%= hidden_field_tag :product_id, product._id %>
	    </div>        
	    <div class="field">
	      User Id<br/>
	      <%= text_field_tag :user_id %>
	    </div>
	    <div class="field">
	      Body
	      <%= text_field_tag :body %>
	    </div>
	<div class="actions">
    	<%= submit_tag("Submit") %>
  	</div>
	<% end %>
</div>
</div>
<br />
<% end %>




<script>
 $(function(){
   $('.myclassname .mylink').click(function(){
      $(this).show();
      $('.myclassname .field').toggle();
      $('.myclassname .actions').toggle();
      return false;
   });
});
</script>

app/views/products/new.html.erb
<h1>New product</h1>
<br />
<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p>
  <b>Business name:</b>
  <%= @product.business_name %>
</p>

<p>
  <b>Members:</b>
  <%= @product.members %>
</p>

<p>
  <b>Product name:</b>
  <%= @product.product_name %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <b>Product url:</b>
  <%= @product.product_url %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>

  <% @product.offers.each do |prod_offer| %>       
    <p>   
      <b>price discount:</b>
      <%= prod_offer.price_discount %>
    </p> 
    <p>
      <b>minimum order quantity:</b>
      <%= prod_offer.min_no_of_buyer %>
    </p>
  <% end %>



<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/products/solar.html.erb
<%= javascript_include_tag "http://maps.google.com/maps/api/js?sensor=false",'google_map' %>
<div class="offer_solar_main_page">
    <div class="offer_use_solar_main_text">
      Offerussolar.com negotiates great solar deals for community groups.
    </div>
  <div class="solar_logo_img"><%=  image_tag("/assets/solar_logo.png") %></div>
    <div class="solar_video"><iframe src="http://player.vimeo.com/video/26905273?title=0&amp;byline=0&amp;autoplay=0&amp;loop=0" width="470" height="281" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>
     <div class="solar_group_join_text">
      Join on offerussolar.com group, and watch as you receive better offers as your group grows!
    </div>
    <div class="get_started">
        <div class="get_started_text">Get started!</div>
          <p class="quick_color">(its quick,easy and free)</p>
        <div class="get_started_inner_border"></div>
        <div class="post_code_text">enter your postcode and click start</div>
          <%= form_tag product_group_products_path , :methods => 'post' do %>
            <div class="start_search">
              <input type="hidden" name="product[street_address]" value="" id="street_address" />
              <input type="hidden" name="product[suburb]" value=""  id="suburb" />
              <input type="text" name="product[zipcode]" value="" id="postcode_quote" autocomplete ="off"  />
            </div>
            <div class="field" style="display:none;">
              <select name="product[state]" id="state" style="width: 210px;">
                      <option value=""></option>
                      <option value="ACT" >ACT</option>
                      <option value="NSW" >NSW</option>
                      <option value="NT" >NT</option>
                      <option value="QLD" >QLD</option>
                      <option value="SA" >SA</option>
                      <option value="TAS" >TAS</option>
                      <option value="VIC" >VIC</option>
                      <option value="WA" >WA</option>
              </select>
            </div>
            <div class="start_button">
              <input type="hidden" name="product[map_lat]" id="map_lat" value="" />
              <input type="hidden" name="product[map_lng]" id="map_lng" value="" />
              <input type="submit" name="product[submit1]" value="Start"/>
            </div>
          <% end %>
        <div  id="map_container" style="width: 200px; height: 200px; display: none;"></div>
    </div>
</div>


<div class="easy_steps">
    <div class="easy_steps_heading">How it works-4 easy steps</div>
    <div class="join_solar">
        <div class="join_solar_img"><%= link_to image_tag("/assets/join.png") %></div>
        <p class="join_solar_img_text">1.Join a solar buying group in your area</p>
    </div>
    <div class="invite_solar">
        <div class="invite_solar_img"><%= link_to image_tag("/assets/invite_img.png") %></div>
        <p class="invite_solar_img_text">2.Invite others to increase your buying power</p>
    </div>
    <div class="discount_group_offer">
        <div class="discount_group_offer_img"><%= link_to image_tag("/assets/discount_offer_img.png") %></div>
        <p class="discount_group_offer_img_text">3.Receive discounted group offer.</p>
    </div>
    <div class="choose_offer">
        <div class="choose_offer_img"><%= link_to image_tag("/assets/chose_offer.png") %></div>
        <p class="choose_offer_img_text">4.Compare, choose an offer and save</p>
    </div>
</div>


 

app/views/products/solar_group_offers.html.erb
<%= javascript_include_tag "http://maps.google.com/maps/api/js?sensor=false",'google_map' %>

<div class="group_text_header">
    <div class="group_location_text">Showing group near <%= params[:zipcode]  %> ,South Australia</div>
    <div class="group_offer_post_code_text">Postcode</div>
    <div class="group_offer_post_code_input_box">
      <input type="text" />
    </div>
    <div class="group_post_search"><input type="button" value="search"/></div>
</div><br /> <br/>
  <%  @zipcode.product_groups.each do |each_product_group| %>
  <% if each_product_group.zipcode == params[:zipcode] %>
  
  <div class="group_details_container">
      <div class="location_of_group">
        <div  id="map_container" data-latitude="<%= @searched_group.map_lat %>" data-longitude="<%= @searched_group.map_lng %>" style="width: 240px;height: 195px;">
        
        </div>
<%#= image_tag "http://maps.google.com/maps/api/staticmap?center=37.386052,-122.083851&zoom=13&markers=37.386052,-122.083851&size=572x470&sensor=false" %> </div>
      <div class="location_of_country">
        <a href="#" class="link_for_location_of_country">Solar power systems</a> <%= params[:zipcode] %> in Adelaide,South Australia
      </div>
      <div class="description_for_tribe">If you're in this area,you can join this solar buying group to receive group discount offers on home solar systems for:</div>

        <div class="member_count_box"><br />
          <span class="number_dimension"><center>X</center></span>
          <span class="member_font"><center>people</center></span>
        </div>
      <div class="offer_details"><br />
        <span class="offer_count"><center><%= @product.offers.count %></center></span>
        <span class="offer_text"><center>offers</center></span>
      </div>
      <div class="time_left_details"><br />
        <span class="time_left"><center>12</center></span>
        <span class="time_left_text"><center>days left</center></span>
      </div>
      <div class="view_this_group"><input type="button" value="View group" /></div>
    
  </div>
  
 
  
 
   <% end %>
<% end %>
   

app/views/products/solar_new_group_offers.html.erb
<%= javascript_include_tag "http://maps.google.com/maps/api/js?sensor=false",'google_map' %>
<div class="group_text_header">
    <div class="group_location_text">Showing group near <%= params[:zipcode]  %> ,South Australia</div>
    <div class="group_offer_post_code_text">Postcode</div>
    <div class="group_offer_post_code_input_box">
      <input type="text" />
    </div>
    <div class="group_post_search"><input type="button" value="search"/></div>
</div><br /> <br/>
<div class="new_group_text">You're the first in this area to participate in an offersolar community buying program! </div>
  <div class="new_group_details_container">
      

      <div class="new_location_of_group"><div  id="map_container" data-latitude="<%= @searched_group.map_lat %>" data-longitude="<%= @searched_group.map_lng %>"style="width: 240px;height: 195px;"></div>
<%#= image_tag "http://maps.google.com/maps/api/staticmap?center=37.386052,-122.083851&zoom=13&markers=37.386052,-122.083851&size=572x470&sensor=false" %> </div>
      <div class="new_location_of_country">
        Join a new group for Adelaide,<%= params[:zipcode] %> South Australia
      </div>
      <div class="new_description_for_tribe">If this is your area,click 'Get Started' with your local solar buying group.We'll help the group grow  and attract great group discount.</div>

        <div class="new_group_box"><br />
          <span class="group_font"><center>new group</center></span>
        </div>
      <div class="new_offer_details"><br />
        <span class="new_offer_count"><center>0</center></span>
        <span class="new_offer_text"><center>offers</center></span>
      </div>
      <div class="time_left_details"><br />
        <span class="time_left"><center>12</center></span>
        <span class="time_left_text"><center>days left</center></span>
      </div>
      <div class="get_started_btn"><input type="button" value="Get started!" /></div>
    
   </div>