config/routes.rb
Tribally::Application.routes.draw do
 
resources :locations

ActiveAdmin.routes(self)

devise_for :admin_users, ActiveAdmin::Devise.config

resources :products do
	collection do 
		post "add_comment"
    post "create_offer"
    get "solar"
    post "product_group"
    get "solar_offers"
    get "solar_group_offers"
    get "solar_new_group_offers"
    #post "solar_offers"
	end
end

resources :businesses do
  collection do
    get "business_signup"
  end
end

  
resources :tribes do
    collection do
      get "change_invitation_status"
      get "my_tribe"
      get "tribe_products"
      get "i_want_this"
      post "invite_friend"
      get "solar"
     end
end
 


  root :to => "products#solar"
  devise_for :users,  :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  #devise_scope :user do
  #  get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  #end
  resources :users, :only => [:show, :index]
end

app/views/layouts/_browse_tribe_menu.html.erb
<table>
  <td>
<div class="sub_navbar">
  <div class="navbar">
    <div class="navbar-inner">
      <div class="container">

        <ul class="nav">
          <li class="sub_menu_first"><%= link_to "Tribe home" %></li>
          <li class="dropdown pull-right sub_menu_second">
            <!--
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">All products<b class="caret"></b> </a>
            -->
            <%= link_to "All products", products_path, :class => 'dropdown-toggle' %>
            <ul class="dropdown-menu">
              <li><%= link_to "drop down 1" %></li>
              <li><%= link_to "drop down 2" %></li>
              <li><%= link_to "drop down 3" %></li>
              <li><%= link_to "drop down 4" %></li>
            </ul>
          </li>
          <li class="dropdown pull-right sub_menu_third">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Contact<b class="caret"></b> </a>
            <ul class="dropdown-menu">
              <li><%= link_to "drop down 1" %></li>
              <li><%= link_to "drop down 2" %></li>
            </ul>
          </li>
          <li>
          <form class="navbar-search pull-right">  	
            <input type="text" class="search-query" placeholder="Search this tribe"/>
          </form> 
          </li>
          <li class="dropdown pull-right sub_menu_fourth">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"></a>
            <ul class="dropdown-menu">
              <li><%= link_to "search 1" %></li>
              <li><%= link_to "search 2" %></li>
            </ul>
          </li>
          <li class="sub_menu_fifth"></li>
        </ul>
      </div>
    </div>
  </div>
</div>
  </td>
  <% if user_signed_in? %>
  <td>
    <%  if current_user.image_url? %>
      <%= image_tag current_user.image_url, :class => 'current_user_iamge' %>
    <% else %>
      <%=  image_tag "/assets/image_thumb.png", :class => 'current_user_iamge' %>
    <% end %>
  </td>
  <td class="current_user_name">
    Logged in as <br />
    <b><%= current_user.fname %></b>
  </td>
  <% else %>
  <td> </td>
  <% end %>
</table>

app/views/layouts/_footer.html.erb
<!--<div class="easy_steps">
    <div class="easy_steps_heading">How it works-4 easy steps</div>
    <div class="join_solar">
        <div class="join_solar_img"><%= link_to image_tag("/assets/join.png") %></div>
        <p class="join_solar_img_text">1.Join a solar buying group in your area</p>
    </div>
    <div class="invite_solar">
        <div class="invite_solar_img"><%= link_to image_tag("/assets/invite_img.png") %></div>
        <p class="invite_solar_img_text">2.Invite others to increase your buying power</p>
    </div>
    <div class="discount_group_offer">
        <div class="discount_group_offer_img"><%= link_to image_tag("/assets/discount_offer_img.png") %></div>
        <p class="discount_group_offer_img_text">3.Receive discounted group offer.</p>
    </div>
    <div class="choose_offer">
        <div class="choose_offer_img"><%= link_to image_tag("/assets/chose_offer.png") %></div>
        <p class="choose_offer_img_text">4.Compare, choose an offer and save</p>
    </div>
</div>
-->
<!--
<div class="easy_2steps">
    <div class="easy_steps_2heading">2 How it works-4 easy steps</div>
    <div class="join_tribe">
        <div class="join_tribe_img"><%= link_to image_tag("/assets/join.png") %></div>
        <p class="join_tribe_img_text">1.Join or create a 'tribe'-a buying group for a product</p>
    </div>
    <div class="invite_others">
        <div class="invite_others_img"><%= link_to image_tag("/assets/invite_img.png") %></div>
        <p class="invite_img_text">2.Invite others to increase your buying power</p>
    </div>
    <div class="receive_group_offer">
        <div class="receive_group_offer_img"><%= link_to image_tag("/assets/group_offer.png") %></div>
        <p class="receive_group_offer_img_text">3.Receive group offers for what you want</p>
    </div>
    <div class="accept_offer">
        <div class="accept_offer_img"><%= link_to image_tag("/assets/accept_offer.png") %></div>
        <p class="accept_offer_img_text">4.Accept an offer to save</p>
    </div>
</div>

-->










  <div class="footer_box"></div>
<div class="footer_container">
   <div class="footer_inner_container">
     <div class="About_link_footer">About

            <div class="about_footer_page"><%= link_to "About us", '#' %></div>
            <div class="about_footer_page"><%= link_to "privacy"%></div>
            <div class="about_footer_page"><%= link_to "Terms and conditions"%> </div>
     </div>
      <div class="for_solar_retailers">
          <div class="text_for_solar_retailers">For solar retailers</div>
          <div class="link_making_offers"><%= link_to "Making offers to group", "#"%></div>
      </div>
      <div class="get_in_touch_container">
          <div class="get_in_touch_text">Get in touch</div>
          <div class="contact_us_link"><%= link_to "Contact us", "#" %></div>
      </div>
      <div class="solar_img">
        <%=  image_tag("/assets/solar_logo.png") %>
      </div>
        <div class="offerus_solar_title"><%= image_tag("/assets/offerussolar.png") %></div>
   </div>

    <div class="footer_last">
      <div class="copy_right_link">Copyright 2012 Michael Dawson Enterpise Pvt Ltd</div>
    </div> 
</div>


<!--
<h1>2 nd footer</h1>
 <div class="footer_inner_2container">
  
  <div class="About_link_2footer">About
     
          <div class="about_2footer_page"><%= link_to "About us", '#' %></div>
          <div class="about_2footer_page"><%= link_to "privacy"%></div>
          <div class="about_2footer_page"><%= link_to "Terms and conditions"%> </div>
  </div>
    <div class="for_business">
        <div class="text_for_business">For businesses</div>
        <div class="link_tribes_offers"><%= link_to "Making offers to tribes", "#"%></div>
    </div>
    <div class="get_in_touch_2container">
        <div class="get_in_touch_2text">Get in touch</div>
        <div class="contact_us_2link"><%= link_to "Contact us", "#" %></div>
    </div>
    <div class="offer_us_img">
      <%=  image_tag("/assets/offer_us.png") %>
    </div>
      
 </div>

  <div class="footer_2last">
    <div class="copy_right_2link">Copyright 2012 Michael Dawson Enterpise Pvt Ltd</div>
  </div>

app/views/layouts/_global_menu.html.erb
<div class="navigation">

    <div class="navigation_container">
      
      <ul class="solar_navi">
        <li class="local_group"><%= link_to "Local groups"%></li>
        <li class="my_group"><%= link_to "My group" %></li>
        <li class="how_it_works"><%= link_to "How it works" %></li>
          <li class="help"><%= link_to "Help" %></li>
      </ul>
    </div>
 
</div> 



<!--
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      
      <ul class="nav">
        <li class="menu_first"><%= link_to "Browse tribes", tribes_path %></li>
        <li class="menu_second"><%= link_to "Start a tribe", new_tribe_path %></li>
        <li class="dropdown pull-right menu_third">
          <%= link_to "My tribes", my_tribe_tribes_path %>
          <!--
<a href="/my_tribe_tribes" class="dropdown-toggle" data-toggle="dropdown"> My tribes <b class="caret"></b> </a>
<ul class="dropdown-menu">
<li><%#= link_to "drop down 1" %></li>
<li><%#= link_to "drop down 2" %></li>
<li><%#= link_to "drop down 3" %></li>
<li><%#= link_to "drop down 4" %></li>
</ul>
--><!--
        </li>
        <li class="menu_fourth"><%= link_to "How it works" %></li>
        <li class="dropdown pull-right menu_fifth">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Help <b class="caret"></b> </a>
          <ul class="dropdown-menu">
            <li><%= link_to "drop down 1" %></li>
            <li><%= link_to "drop down 2" %></li>
          </ul>
        </li>
        <li>
        <form class="navbar-search pull-right">
          <input type="text" class="search-query" placeholder="Search tribal.ly"/>
        </form>
        </li>
        <li class="dropdown pull-right menu_sixth">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"></a>
          <ul class="dropdown-menu">
            <li><%= link_to "search 1" %></li>
            <li><%= link_to "search 2" %></li>
          </ul>
        </li>
        <li class="menu_seventh"></li>
      </ul>
    </div>
  </div>
</div>
-->

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">×</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<table class="main_navigation">
  <td>
    <%= link_to image_tag("/assets/offerus_main_logo.png"), root_path, :class => 'brand' %>
  </td>
 
  <td class="login_navigation">
    <% if user_signed_in? %>
      <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>           
    <% else %> 
      <div id="loginContainer">
        <div id="loginButton">
          <div class="span">Login</div>
        </div>
          <div style="clear:both"></div>
          <div id="loginBox">
            <div class="main_loginForm">
              <div id="loginForm">
                <% if defined? resource %>
                 <%= form_for(resource, :as => resource_name, :html =>{ :autocomplete => "off"}, :url => session_path(resource_name)) do |f| %>
                  <div class="signin_input"><%= f.email_field :email, :placeholder => 'Email' %></div>

                  <div  class="signin_input"><%= f.password_field :password, :placeholder => 'Password' %></div>
                      
                  <div class="login_checkbox">
                    <% if devise_mapping.rememberable? -%>
                      <table>
                      <td>
                        <%= f.check_box :remember_me %>
                      </td>
                      <td>
                        Remember me
                      </td>
                      </table>
                    <% end -%>
                  </div>
                </div>
                  <div class="sign_in_btn_window">
                    <%= f.submit "Sign in", :class => 'btn btn-primary' %>
                  </div>
                  <% end %>
                  <div class="forget_password_text">
                    <%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
                      <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
                    <% end -%>
                  </div>
                  <% end %> 
            </div>
          </div>
      </div>
    <% end %>
  </td>
  
  <td class="sign_up_navigation">
    <% if user_signed_in? %>
      <%= link_to 'Edit account', edit_user_registration_path %>
      <% if current_user.has_role? :admin %>
        <%= link_to 'Admin', users_path %>
      <% end %>
    <% else %>
      <%= link_to image_tag("/assets/facebook_login.png"), user_omniauth_authorize_path(:facebook, :display=>"popup"), :class => "popup facebook_navigation_top", :"data-width" => 600, :"data-height" => 400 %>
      <%= link_to 'Sign up', new_user_registration_path %>
    <% end %>
  </td>
</table>
<div id="fb-root"></div>
  <script>  										       
    window.fbAsyncInit = function() {
      FB.init({     
        appId      : '395920417135166', // App ID
        //channelUrl : '//WWW.YOUR_DOMAIN.COM/channel.html', // Channel File
        status     : true, // check login status
        cookie     : true, // enable cookies to allow the server to access the session
        xfbml      : true  // parse XFBML
      });

      // Additional initialization code here
    };

    // Load the SDK Asynchronously
    (function(d){
      var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
      js = d.createElement('script'); js.id = id; js.async = true;
      js.src = "//connect.facebook.net/en_US/all.js";
      d.getElementsByTagName('head')[0].appendChild(js);
      }(document));

    // Load the SDK Asynchronously
    function popupCenter(url, width, height, name) {
    var left = (screen.width/2)-(width/2);
    var top = (screen.height/2)-(height/2);
    return window.open(url, name, "menubar=no,toolbar=no,status=no,width="+width+",height="+height+",toolbar=no,left="+left+",top="+top);
    }

    $("a.popup").click(function(e) {
      popupCenter($(this).attr("href"), $(this).attr("data-width"), $(this).attr("data-height"), "authPopup");
      e.stopPropagation(); return false;
    });
    if(window.opener) {
        window.opener.location.reload(true);
        window.close()
      }
  </script>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Tribally" %></title>
    <meta name="description" content="">
    <meta name="author" content="">

    <%= stylesheet_link_tag  "application", "main", :media => "all" %>    
    <%= javascript_include_tag "application","rails.validations","jquery.min" %>

    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body id="main_background">    
    <div>
      <div class="container">                
          <div>              
            <%= render 'layouts/navigation' %>            
          </div>        
        <div>
          <%= render 'layouts/global_menu' %>
        </div>
        <div class="main_body">
          <%= render 'layouts/messages' %>
          <%= yield %>
        </div>
     
        <%= render 'layouts/footer' %>
      
      </div>
      
     

   </div>
  </body>
</html>